apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "jayaks1"
    labels:
        app: "jayaks1"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: jayaks1a3e9-jayaks1.86bc0f3032bc4400a134.eastus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "jayaks1"
                servicePort: 8080